# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Cache Node Modules
      uses: actions/cache@v1.1.2
      env:
        cache-name: cache-node-modules
      with:
        # A directory to store and save the cache
        path: ~/.npm
        # An explicit key for restoring and saving the cache
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
    
    - name: Installing packages
      run: yarn install --silent
    - name: Linting
      run: yarn lint 
    - name: Build
      run: yarn build --if-present
    - name: Loging into Vercel
      run: vercel login regiswareja@gmail.com
    - name: Deploying
      run: vercel
    
